
  CREATE TABLE "EZIAUS"."ZZ_UNIT_TEST" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"REFERENCE_NUMBER" NUMBER(10,0), 
	"CREATED_BY" VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
	"CREATED_DATETIME" DATE DEFAULT SYSDATE, 
	"MODIFIED_BY" VARCHAR2(30 BYTE) DEFAULT 'SYSTEM', 
	"MODIFIED_DATETIME" DATE DEFAULT SYSDATE, 
	"ROW_VERSION" NUMBER(10,0) DEFAULT '0', 
	"IS_DELETED" NUMBER(1,0) DEFAULT '0', 
	 CONSTRAINT "ZZ_UNIT_TEST_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EZI_INDEX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EZI_DATA" ;

  CREATE INDEX "EZIAUS"."ZZ_UNIT_TEST_IS_DEL" ON "EZIAUS"."ZZ_UNIT_TEST" ("IS_DELETED") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "EZI_INDEX" ;

  CREATE OR REPLACE EDITIONABLE TRIGGER "EZIAUS"."ZZ_UNIT_TEST_UPD" 
BEFORE UPDATE ON ZZ_UNIT_TEST
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW	  
BEGIN
		
	:NEW.ROW_VERSION := :OLD.ROW_VERSION + 1;  
  
	:NEW.MODIFIED_DATETIME := Sysdate;
	:NEW.MODIFIED_BY := GET_USER();
		
END ZZ_UNIT_TEST_UPD;
/
ALTER TRIGGER "EZIAUS"."ZZ_UNIT_TEST_UPD" ENABLE;

  CREATE OR REPLACE EDITIONABLE TRIGGER "EZIAUS"."ZZ_UNIT_TEST_INS" 
BEFORE INSERT ON ZZ_UNIT_TEST
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW  
BEGIN

    IF NVL(:NEW.ID, 0) = 0 THEN
      SELECT ZZ_UNIT_TEST_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  
	:NEW.ROW_VERSION := 1;
    
	:NEW.MODIFIED_DATETIME := Sysdate;
	:NEW.MODIFIED_BY := GET_USER();

	:NEW.CREATED_DATETIME := Sysdate;
	:NEW.CREATED_BY := GET_USER();
  
END ZZ_UNIT_TEST_INS;
/
ALTER TRIGGER "EZIAUS"."ZZ_UNIT_TEST_INS" ENABLE;
